### PR TITLE
Add new tests

### PR DESCRIPTION
**Pull request by yygf123**
# Environment

- Python: 3.9
- CPU: AMD Ryzen 7 4800H with Radeon Graphics
- GPU: NVIDIA GeForce RTX 2060

# Test Content

- Create test_nvar.py to test nvar.py.
- Create test_reservoir.py to test reservoir.py.
- Create test_rnncells.py to test rnncells.py.
- Create test_mode.py to test whether each dnn function supports TrainingMode, BatchingMode and NonBatchingMode.

# Results
## rnncells.py

- Conv1dLSTMCell, Conv2dLSTMCell and Conv3dLSTMCell do not support NonBatchingMode.
- Other functions all support TrainingMode, BatchingMode and NonBatchingMode.

## reservoir.py

- All the functions support TrainingMode, BatchingMode and NonBatchingMode.

## conv.py

- Conv1d, Conv2d, Conv3d, ConvTranspose1d, ConvTranspose2d, ConvTranspose3d do not support NonBatchingMode.
- Other functions all support TrainingMode, BatchingMode and NonBatchingMode.

## pooling.py
- All the functions support TrainingMode, BatchingMode and NonBatchingMode.

## dropout.py
- All the functions support TrainingMode, BatchingMode and NonBatchingMode.

## function.py
- All the functions support TrainingMode, BatchingMode and NonBatchingMode.

## linear.py
- All the functions support TrainingMode, BatchingMode and NonBatchingMode.

## normalization.py
- BatchNorm1d, BatchNorm2d, BatchNorm3d do not support NonBatchingMode.
- Other functions all support TrainingMode, BatchingMode and NonBatchingMode.

### CODE REVIEW

**Review by chaoming0625 — CHANGES_REQUESTED** [review]
Good work.

The test errors are caused by the ignore of adding ``bm.random.seed()`` before the test cases of RNNCell.

**Comment by chaoming0625** [comment]
Test error in Python 3.8:

image

**Comment by chaoming0625** [comment]
Test errors on Python 3.9 - 3.11 are caused by the JAX compatible issue since the latest release of JAX removes the support of `Array.split`.

**Comment by yygf123** [comment]
I have already update the tests. And the automatic actions have passed.

**Pull request merged**
