### PR TITLE
fix bugs in `brainpy.math.random.truncated_normal`

### PR DESCRIPTION
**Pull request by chaoming0625**
- fix bugs in `brainpy.math.random.truncated_normal`
- copy random doc of numpy for better readability

### CODE REVIEW

**Review by charlielam0615 — CHANGES_REQUESTED** [review]
See comments and happy new year!

**Comment by chaoming0625** [comment]
Have changed the algorithm of ``truncated _normal`` sampling using methods from 

- https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf

**Comment by chaoming0625** [comment]
The ``truncated_normal`` is not straightforward to multiply the ``scale`` and shift the ``loc``. I have checked the algorithms and confirmed the results using methods in https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf

**Comment by chaoming0625** [comment]
One more thing, I have add the checking for the valid setting of ``loc``, ``scale``, ``upper``, and ``lower``, in order to avoid the incorrent sampling.

**Pull request merged**
