### PR TITLE
Test of rates

### PR DESCRIPTION
**Pull request by shangyangli**

### CODE REVIEW

**Comment by chaoming0625** [comment]
The tests have failed. Before merging this PR, you should fix the errors first. 

Particularly, the bug fixing should be:

**Comment by chaoming0625** [comment]
At the line of

[`` if bm.any(self.noise_i != 0.):``](https://github.com/brainpy/BrainPy/blob/2f49a5ab07ebbcd50295e1b7300fed90c6eda867/brainpy/_src/rates/populations.py#LL1062C7-L1062C7)

change  it as:

```python

with jax.ensure_compile_time_eval():
  has_noise = bm.any(self.noise_i != 0.)

if has_noise:
  ...
```



Similarly, at the line of ```` if bm.any(self.noise_e != 0.):``, change it as:

```python

with jax.ensure_compile_time_eval():
  has_noise = bm.any(self.noise_e != 0.)

if has_noise:
  ...
```

**Comment by chaoming0625** [comment]
@ztqakita Please help @shangyangli to pass all tests. We cannot merge any PR with test errors.

**Review by ztqakita — APPROVED** [review]
Great!

**Pull request merged**
