### PR TITLE
Reconstruct BrainPy documentations

### PR DESCRIPTION
**Pull request by ztqakita**
Reconstruct the documentation in a more simple and neat way.
image

### CODE REVIEW

**Review by chaoming0625 — APPROVED** [review]
Great ztqakita !

**Comment by chaoming0625** [comment]
I solved a conflict, and added the surrograte gradient tutorial of @Routhleck in the toolbox panel.

**Comment by chaoming0625** [comment]
Although I have merged this PR into the master, I expect there are bugs, since the requirements are not updated. @ztqakita

**Comment by Routhleck** [comment]
> I solved a conflict, and added the surrograte gradient tutorial of @Routhleck in the toolbox panel.

Got it!

**Pull request merged**
